# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - reset.min.css
    - main.css
    - vendor/jquery.qtip.min.css

  javascripts:
    - vendor/jquery-1.7.2.min.js
    - vendor/jquery.qtip.min.js
    - tooltip.js

  has_layout:     true
  layout:         layout
