# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Code review tool for git projects > Crew
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - reset.min.css
    - vendor/jquery.qtip.min.css
    - main.less: { rel: stylesheet/less }

  javascripts:
    - vendor/less-1.1.5.min.js
    - vendor/jquery-1.6.4.min.js
    - vendor/jquery.fracs.js
    - vendor/jquery.qtip.min.js
    - toggleState.js
    - context.js
    - commentGlobal.js
    - button.js

  has_layout:     true
  layout:         layout
