# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Code review tool for git projects > Crew
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - reset.min.css
    - vendor/jquery.qtip.min.css
    - main.css

  javascripts:
    - vendor/jquery-1.7.2.min.js
    - vendor/jquery.qtip.min.js
    - vendor/jquery.mousewheel.min.js
    - vendor/bootstrap-dropdown.js
    - itemStatusAction.js
    - commentGlobal.js
    - tooltip.js

  has_layout:     true
  layout:         layout
